<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="Assets\light\bell.svg" />
    <None Remove="Assets\light\leftBtn.svg" />
    <None Remove="Assets\light\rightBtn.svg" />
    <None Remove="Assets\sideBarBtn.svg" />
    <None Remove="Fonts\COPYRIGHT.txt" />
    <None Remove="Fonts\timesnewromanpsmt.ttf" />
    <None Remove="Fonts\timesnewromanps_italicmt.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Controls.TreeDataGrid" Version="11.0.2" />
    <PackageReference Include="Avalonia.Skia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.0.0.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.10" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.10.4" />
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.0.10.4" />
    <PackageReference Include="Avalonia.Xaml.Interactions.Custom" Version="11.0.10.4" />
    <PackageReference Include="itext" Version="8.0.3" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="8.0.3" />
    <PackageReference Include="itext.bouncy-castle-fips-adapter" Version="8.0.3" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.1.5.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Helper\Helper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Styles\Desktop\TextBoxes\PasswordBox.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fonts\COPYRIGHT.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\timesnewromanpsmt.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\timesnewromanps_italicmt.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Update="Styles\Desktop\TreeViews\Headers.axaml">
      <SubType>Designer</SubType>
    </AvaloniaXaml>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\DutyChartList.axaml.cs">
      <DependentUpon>DutyChartList.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\RegistrationView.axaml.cs">
      <DependentUpon>RegistrationView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
