<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <WasmMainJSPath>AppBundle\main.js</WasmMainJSPath>
    <OutputType>Exe</OutputType>
	<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <WasmExtraFilesToDeploy Include="AppBundle\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" Version="11.0.10" />
	  <PackageReference Include="Avalonia" Version="11.0.10" />
	  <PackageReference Include="Avalonia.Controls.TreeDataGrid" Version="11.0.2" />
	  <PackageReference Include="Avalonia.Skia" Version="11.0.10" />
	  <PackageReference Include="Avalonia.Svg.Skia" Version="11.0.0.18" />
	  <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
	  <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
	  <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.10" />
	  <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.10" />
	  <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.10.4" />
	  <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.0.10.4" />
	  <PackageReference Include="Avalonia.Xaml.Interactions.Custom" Version="11.0.10.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\Client\Client.csproj" />
  </ItemGroup>
</Project>
